language: python
python:
  - 2.7
  - 3.4
before_script:
  - mysql -e 'create database flask_blogging;'
  - psql -c 'create database flask_blogging;' -U postgres;
install:
  - pip install -e .
  - pip install coverage pep8 mysqlclient==1.3.6 psycopg2
script:
  - nosetests --with-coverage --cover-package=flask_blogging --cover-min-percentage=85 -v
  - pep8 --repeat flask_blogging/ test/
notifications:
  email: false
